repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
        exclude: assets/preview.gif
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  -   repo: https://github.com/biomejs/pre-commit
      rev: "v0.1.0"  # Use the sha / tag you want to point at
      hooks:
      -   id: biome-check
          additional_dependencies: ["@biomejs/biome@1.4.1"]
  - repo: local
    hooks:
      - id: next-lint
        name: next lint
        entry: next lint packages/nextjs --fix --max-warnings 0 --dir .
        language: node
        pass_filenames: false
        additional_dependencies:
          - next
          - typescript
          - "@types/react"
          - "@types/node"
  - repo: local
    hooks:
      - id: solhint
        name: solhint
        entry: solhint packages/hardhat/contracts/**/*.sol --config packages/hardhat/.solhint.json
        language: node
        pass_filenames: false
        additional_dependencies: ["solhint@4.5.2"]
  - repo: local
    hooks:
      - id: eslint
        name: eslint
        entry: eslint packages/hardhat --fix --max-warnings 0
        language: node
        pass_filenames: false
        additional_dependencies:
          - "eslint@8.56.0"
          - "@typescript-eslint/parser"
          - "@typescript-eslint/eslint-plugin"
          - "@types/node"
          - typescript
