repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--ignore-path", ".gitignore"]
  - repo: local
    hooks:
      - id: next-lint
        name: next lint
        entry: next lint packages/nextjs --fix --max-warnings 0 --dir .
        language: node
        pass_filenames: false
        additional_dependencies:
          [
            "next@14.1.0",
            "eslint-plugin-prettier@5.1.3",
            "eslint-config-prettier@9.1.0",
            "typescript@5",
            "@types/react@18",
            "@types/node@20",
          ]
  - repo: local
    hooks:
      - id: solhint
        name: solhint
        entry: solhint packages/hardhat/contracts/**/*.sol --config packages/hardhat/.solhint.json
        language: node
        pass_filenames: false
        additional_dependencies: ["solhint@4.5.2"]
  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.56.0
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        types: [file]
        additional_dependencies:
          - eslint@8.56.0
          - eslint-config-prettier@9.1.0
          - eslint-plugin-prettier@5.1.3
          - "@typescript-eslint/parser@7.0.1"
          - "@typescript-eslint/eslint-plugin@7.0.1"
          - "@types/node@20"
          - typescript@5
        args: ["packages/hardhat"]
