repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-added-large-files
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-json
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v4.0.0-alpha.8
    hooks:
      - id: prettier
        args: ["--ignore-path", ".gitignore"]
  - repo: local
    hooks:
      - id: next-lint
        name: next lint
        entry: next lint --fix --max-warnings 0 --dir .
        language: node
        pass_filenames: false
        additional_dependencies:
          [
            "next@14.1.0",
            "eslint-plugin-prettier@5.1.3",
            "eslint-config-prettier@9.1.0",
          ]
