services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - 8545:8545
    command:
      - -m
      - myth like bonus scare over problem client lizard pioneer submit female collect
      - -n

  next:
    image: next/web3:latest
    build: .
    ports:
      - 3000:3000
    environment:
      - WS_PATH=ws://ganache:8545
    depends_on:
      - ganache

  explorer:
    image: alethio/ethereum-lite-explorer:latest
    ports:
      - 80:80
    environment:
      - APP_NODE_URL=http://ganache:8545
    depends_on:
      - ganache
    profiles:
      - debug
