name: Continuous Integration

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Python | Setup
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Pre-commit | Run
        uses: pre-commit/action@v3.0.1

  test:
    name: "End-to-End - Browser: ${{ matrix.browser }}"
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [chromium, firefox]
    steps:
      - name: Git | Checkout
        uses: actions/checkout@v4

      - name: Bun | Setup
        uses: oven-sh/setup-bun@v1

      - name: Bun | Install
        run: |
          bun install --frozen-lockfile

      - name: Docker | Setup
        uses: docker/setup-buildx-action@v3

      - name: Docker Compose | Up
        uses: isbang/compose-action@v1.5.1
        with:
          compose-file: docker-compose.yaml

      - name: Playwright | Run Tests
        run: |
          bun run playwright install --with-deps ${{ matrix.browser }}
          bun run playwright test --project ${{ matrix.browser }}

      - name: Artifact | Upload Results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: playwright-report-${{ matrix.browser }}
          path: playwright-report/
          retention-days: 1
